version: 2

models:
  - name: dim_channels
    columns:
      - name: channel_name
        tests:
          - unique
          - not_null
  - name: dim_dates
    columns:
      - name: date
        tests:
          - unique
          - not_null
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_id
        tests:
          - not_null
      - name: date_id
        tests:
          - not_null 
  - name: fct_image_detections
    columns:
      - name: message_id
        tests:
          - not_null
      - name: detected_object_class
        tests:
          - not_null
      - name: confidence_score
        tests:
          - not_null 